spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_bookstore_management_system
    username: root #set your username
    password: $hyam@123  #set your password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: true
